DROP TABLE IF EXISTS poll_votes CASCADE;
DROP TABLE IF EXISTS poll_options CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS course_materials CASCADE;
DROP TABLE IF EXISTS lectures CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Lectures
CREATE TABLE lectures (
    lecture_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    summary      VARCHAR(2000),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Course Materials
CREATE TABLE course_materials (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecture_id         BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_path   VARCHAR(500) NOT NULL,
    content_type       VARCHAR(100),
    file_size          BIGINT,
    uploaded_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content            BLOB,

    CONSTRAINT fk_course_material_lecture 
        FOREIGN KEY (lecture_id) REFERENCES lectures(lecture_id)
);

-- Users
CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(50) NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email     VARCHAR(120) NOT NULL UNIQUE,
    phone     VARCHAR(30) NOT NULL,
    role      VARCHAR(20) NOT NULL,
    enabled   BOOLEAN NOT NULL DEFAULT TRUE
);

-- Comments
CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id   BIGINT NOT NULL,
    content     CLOB NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_comment_author 
        FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE INDEX idx_target ON comments (target_type, target_id);
CREATE INDEX idx_author ON comments (author_id);

-- Polls
CREATE TABLE polls (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question    VARCHAR(500) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    course_order INT
);

-- Poll Options
CREATE TABLE poll_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id       BIGINT NOT NULL,
    option_text   VARCHAR(300) NOT NULL,
    option_index  INT NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_poll_option_poll 
        FOREIGN KEY (poll_id) REFERENCES polls(id),
    CONSTRAINT uk_poll_option_index 
        UNIQUE (poll_id, option_index)
);

-- Poll Votes (one vote per user per poll, editable)
CREATE TABLE poll_votes (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poll_id            BIGINT NOT NULL,
    voter_id           BIGINT NOT NULL,
    selected_option_id BIGINT NOT NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_poll_vote_poll 
        FOREIGN KEY (poll_id) REFERENCES polls(id),
    CONSTRAINT fk_poll_vote_voter 
        FOREIGN KEY (voter_id) REFERENCES users(id),
    CONSTRAINT fk_poll_vote_option 
        FOREIGN KEY (selected_option_id) REFERENCES poll_options(id),
    CONSTRAINT uk_poll_voter 
        UNIQUE (poll_id, voter_id)
);