DROP TABLE IF EXISTS course_materials;
DROP TABLE IF EXISTS lectures;



create table if not exists lectures (
                                        lecture_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title        VARCHAR(255) NOT NULL,
    summary      VARCHAR(2000)
    --course_order INT--
    );


CREATE TABLE course_materials (
                                  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  lecture_id        BIGINT       NOT NULL,
                                  original_file_name VARCHAR(255) NOT NULL,
                                  content           BLOB,
                                  stored_file_path  VARCHAR(500)  NOT NULL,
                                  content_type      VARCHAR(100),
                                  file_size         BIGINT,
                                  uploaded_at       TIMESTAMP      NOT NULL,

                                  CONSTRAINT fk_course_material_lecture
                                      FOREIGN KEY (lecture_id) REFERENCES lectures(lecture_id)
);

DROP TABLE IF EXISTS user_roles cascade;
DROP TABLE IF EXISTS users cascade    ;


CREATE TABLE IF NOT EXISTS users (
                                     id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username  VARCHAR(50) NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email     VARCHAR(120) NOT NULL UNIQUE,
    phone     VARCHAR(30) NOT NULL,
    role      VARCHAR(20) NOT NULL,
    enabled   BOOLEAN NOT NULL
    );;


CREATE TABLE IF NOT EXISTS user_roles (
                                          user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
                                          username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
    );

DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          author_id   BIGINT       NOT NULL,
                          target_type VARCHAR(20)  NOT NULL,
                          target_id   BIGINT       NOT NULL,
                          content     CLOB         NOT NULL,
                          created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX idx_target ON comments (target_type, target_id);
CREATE INDEX idx_author ON comments (author_id);
